name: megapdf_client
description: Flutter client for MegaPDF API - PDF processing made simple
publish_to: "none"
version: 1.0.0+100

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^15.1.2

  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # File Handling
  file_picker: ^10.1.9
  path_provider: ^2.1.2
  path: ^1.8.3
  open_file: ^3.3.2
  permission_handler: ^12.0.0+1

  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  lottie: ^3.3.1
  window_manager: ^0.4.3

  # Utilities
  equatable: ^2.0.5
  intl: ^0.20.2
  uuid: ^4.2.1

  cupertino_icons: ^1.0.2
  sqflite: ^2.4.2
  device_info_plus: ^11.4.0
  share_plus: ^11.0.0
  syncfusion_flutter_pdfviewer: ^29.2.5
  printing: ^5.14.2
  flutter_file_downloader: ^2.1.0
  app_settings: ^6.1.1
  shared_preferences: ^2.5.3
  flutter_doc_scanner: ^0.0.16
  mailer: ^6.4.1
  in_app_review: ^2.0.10
  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.14.3"
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  retrofit_generator: ^9.2.0
  json_serializable: ^6.7.1

  # Linting
  flutter_lints: ^5.0.0

  # Testing
  mockito: ^5.4.4
  change_app_package_name: ^1.5.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/ic_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/ic_icon.png"
  windows:
    generate: true
    image_path: "assets/icons/ic_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/ic_icon.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
