// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVwsw1CR69NZXYi27GlNYGSU_4WLNhwaQ',
    appId: '1:261978309187:web:19129cf4f5eb0fa3ca8af6',
    messagingSenderId: '261978309187',
    projectId: 'mega-pdf-project',
    authDomain: 'mega-pdf-project.firebaseapp.com',
    storageBucket: 'mega-pdf-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCurAc4OY1j-1cdWcLHMBlQcQeI8fHYyCw',
    appId: '1:261978309187:android:ca550b0bdf7ee772ca8af6',
    messagingSenderId: '261978309187',
    projectId: 'mega-pdf-project',
    storageBucket: 'mega-pdf-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr0FaflShOXGKhg-sqlq8HMcTAtRIOKao',
    appId: '1:261978309187:ios:2d514c67702a442cca8af6',
    messagingSenderId: '261978309187',
    projectId: 'mega-pdf-project',
    storageBucket: 'mega-pdf-project.firebasestorage.app',
    iosBundleId: 'com.mega.pdf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr0FaflShOXGKhg-sqlq8HMcTAtRIOKao',
    appId: '1:261978309187:ios:2d514c67702a442cca8af6',
    messagingSenderId: '261978309187',
    projectId: 'mega-pdf-project',
    storageBucket: 'mega-pdf-project.firebasestorage.app',
    iosBundleId: 'com.mega.pdf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVwsw1CR69NZXYi27GlNYGSU_4WLNhwaQ',
    appId: '1:261978309187:web:bf9c0c9c65bc0a77ca8af6',
    messagingSenderId: '261978309187',
    projectId: 'mega-pdf-project',
    authDomain: 'mega-pdf-project.firebaseapp.com',
    storageBucket: 'mega-pdf-project.firebasestorage.app',
  );
}
